# Generated by Django 5.0.6 on 2024-06-16 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_title', models.CharField(max_length=200)),
                ('event_start_date', models.DateField(default=django.utils.timezone.now)),
                ('event_end_date', models.DateField(default=django.utils.timezone.now)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_duration_time', models.PositiveIntegerField(blank=True, null=True)),
                ('event_organisator', models.CharField(choices=[('ABSA', 'ABSA'), ('BDAA', 'BDAA')], max_length=10)),
                ('quiz', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('price_for_members', models.FloatField(blank=True, null=True)),
                ('price_for_non_members', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
