# Generated by Django 5.0.6 on 2024-06-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quiz_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
