# Generated by Django 5.0.6 on 2024-06-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_quiz_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('webinar_title', 'event_start_date')},
        ),
    ]
