# Generated by Django 5.0.6 on 2024-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_organisator',
            field=models.CharField(choices=[('ABSA', 'ABSA'), ('BDAA', 'BDAA'), ('ABSA/BDAA', 'ABSA/BDAA')], max_length=10),
        ),
    ]
