# Generated by Django 5.0.6 on 2024-06-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_organisator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quiz_URL',
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizTitle', models.CharField(max_length=200)),
                ('quiz_URL', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='events.event')),
            ],
            options={
                'unique_together': {('quizTitle', 'quiz_URL')},
            },
        ),
    ]
