# Generated by Django 5.0.6 on 2024-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_quiz_url_quizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('online', 'Online'), ('canceled', 'Canceled')], default='live', max_length=10),
        ),
    ]
