# Generated by Django 5.0.6 on 2024-06-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_submembershiptype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peoples',
            unique_together={('first_name', 'last_name', 'default_email')},
        ),
    ]
