# Generated by Django 5.0.6 on 2024-06-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_peoples_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipassignment',
            name='membership_ID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
