# Generated by Django 5.0.6 on 2024-06-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membershipassignment_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipassignment',
            name='membership_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
