# Generated by Django 5.0.6 on 2024-09-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0006_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReportFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_reports/')),
                ('report_source', models.CharField(choices=[('Eventbrite', 'Eventbrite'), ('Zoom', 'Zoom'), ('Quiz_Form', 'Quiz_Form')], default='Eventbrite', max_length=30)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
