# Generated by Django 5.0.6 on 2024-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('default_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('optional_email', models.EmailField(blank=True, max_length=254)),
                ('default_chapter', models.CharField(blank=True, max_length=50)),
                ('secondary_chapter', models.CharField(blank=True, max_length=50)),
                ('optional_chapter', models.CharField(blank=True, max_length=50)),
                ('default_state', models.CharField(blank=True, max_length=50)),
                ('secondary_state', models.CharField(blank=True, max_length=50)),
                ('optional_state', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('phone_home', models.CharField(blank=True, max_length=100)),
                ('phone_work', models.CharField(blank=True, max_length=100)),
                ('phone_mobile', models.CharField(blank=True, max_length=100)),
                ('phone_fax', models.CharField(blank=True, max_length=100)),
                ('default_address', models.CharField(blank=True, max_length=300)),
                ('secondary_address', models.CharField(blank=True, max_length=300)),
                ('optional_address', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'default_email')},
            },
        ),
    ]
