# Generated by Django 5.0.6 on 2024-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='phost_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
