eventbrite_excel_fields = [
                        "Order #",	
                        "Order Date",
                        "First Name",	
                        "Surname",	
                        "Email",	
                        "Quantity",	
                        "Price Tier",
                        "Ticket Type",
                        "Attendee #",
                        "Order Type",	
                        "Currency",
                        "Total Paid",
                        "Fees Paid",
                        "Eventbrite",
                        "Fees",
                        "Eventbrite Payment Processing",
                        "Attendee Status",
                        "Mobile Phone",
                        "Birth Date",
                        "Shipping Address 1",
                        "Shipping Address 2",	
                        "Shipping City",
                        "Shipping State/Province",
                        "Shipping Postcode",
                        "Shipping Country"
]